version: '3.9'

networks:
  faisaldev:


services:
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./backend:/app/api
    networks:
      - faisaldev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:3000
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
      - /app/frontend/.nuxt 
    restart: unless-stopped
    networks:
      - faisaldev

  mysql:
    image: mysql:8.0.32
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - faisaldev
    environment:
      MYSQL_DATABASE: faisaldev
      MYSQL_USER: faisaldev
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICES_TAGS: dev
      SERVICES_NAME: mysql

  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/app/api
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - faisaldev
